import LocalizedStrings from "react-native-localization";

let strings = new LocalizedStrings({
  "en-US": {
    Login: "LOGIN",
    Get_Lucky: "Get Lucky CSP",
    mainProfile: "Profile",
    mainBooking: "Booking",
    mainInbox: "Inbox",
    mainGallery: "Gallery",
    mainSetting: "Settings",
    mainSubscription: "Subscription",
    profiletab_Profile: "Profile",
    profiletab_Reviews: "Reviews",
    profiletab_Services: "Services",
    profileupdate_Name: "Name",
    profileupdate_Mobile_Number: "Mobile Number",
    profileupdate_Bussiness: "Bussiness",
    profileupdate_Address: "Address",
    profileupdate_Description: "Description",
    serchplacescreen_Search_a_places: "Enter your Address:",
    servicescreen_No_Services_are_available_for_you:
      "No Services are available for you!",
    bookingtab_Waiting: "Waiting",
    bookingtab_Booked: "Booked",
    bookingtab_Complete: "Completed",
    waitingscreen_Service_Type: "Service Type:",
    waitingscreen_Mobile_Number: "Mobile Number:",
    waitingscreen_Comment: "Comment:",
    waitingscreen_Time: "Time:",
    waitingscreen_Customer_work_request_time: "Customer work request time",
    waitingscreen_Work_offer_time: "Work offer time",
    waitingscreen_Enter_price: "Enter price",
    waitingscreen_Enter_your_comment_Optional: "Enter your comment (Optional)",
    bookingscreen_Charges: "Charges:",
    bookingscreen_Comment: "Comment:",
    settingscreen_Notification: "Notification",
    settingscreen_Contact_us: "Contact Us",
    settingscreen_Logout: "Logout",
    contactusscreen_Subject: "Subject",
    contactusscreen_Details: "Details",
    subscriptionscreen_Cancel_Subscription: "Cancel Subscription",
    subscriptionscreen_Subscription_fee: "Subscription fee:",
    subscriptionscreen_per_Month: "per Month",
    subscriptionscreen_Yearly: "Yearly \n Save upto 15% with an yearly plan",
    subscriptionscreen_Monthly: "Monthly",
    subscriptionscreen_Enter_Year: "Enter Year",
    subscriptionscreen_Enter_Month: "Enter Month",
    subscriptionscreen_Total_fee: "Total fee:",

    //SURE?
    sure_Are_you_sure_to_exit: "Are you sure to exit?",
    sure_Are_you_sure_to_delete: "Are you sure to delete?",
    sure_Are_you_sure_to_reject: "Are you sure to reject?",
    sure_Are_you_sure_to_unsubsribe_services:
      "Are you sure to unsubsribe services?",
    sure_Work_Completed: "Work Completed?",

    // BUTTONS
    button_Click_to_Upload_Image: "Click to Upload Image",
    button_Save: "Save",
    button_Exit: "Exit",
    button_Add: "Add",
    button_Update: "Update",
    button_Send: "Send",
    button_Apply: "Apply",
    button_Reject: "Reject",
    button_Accept: "Accept",
    button_Message: "Message",
    button_Delete: "Delete",
    button_Help: "Help",
    button_OK: "OK",
    button_Cancel: "Cancel",
    button_Yes: "Yes",
    button_No: "No",
    button_Submit: "Submit",
    button_Done: "Done",
    button_Close: "Close",
    button_Finish: "Finish",
    button_Continue_with_facebook: "Continue with facebook",
    button_Cancel_All: "Cancel All",
    button_Paypal_Check_Out: "Paypal Check Out",

    //others
    No_Booked_Request_Yet: "No Booked Request Yet!",
    No_order_is_completed_yet: "No order is completed yet!",
    Fees: "Fees:",
    Your_Expertise: "Your Expertise?",
    Select_Image: "Select Image",
    No_image_uploaded_yet: "No image uploaded yet!",
    Tone: "Tone",
    Silent: "Silent",
    No_Internet_Connection_Available: "No Internet Connection Available!",
    No_Review_is_placed_yet: "No Review is placed yet!"
  },
  en: {
    Login: "LOGIN",
    Get_Lucky: "Get Lucky CSP",
    mainProfile: "Profile",
    mainBooking: "Booking",
    mainInbox: "Inbox",
    mainGallery: "Gallery",
    mainSetting: "Settings",
    mainSubscription: "Subscription",
    profiletab_Profile: "Profile",
    profiletab_Reviews: "Reviews",
    profiletab_Services: "Services",
    profileupdate_Name: "Name",
    profileupdate_Mobile_Number: "Mobile Number",
    profileupdate_Bussiness: "Bussiness",
    profileupdate_Address: "Address",
    profileupdate_Description: "Description",
    serchplacescreen_Search_a_places: "Enter your Address:",
    servicescreen_No_Services_are_available_for_you:
      "No Services are available for you!",
    bookingtab_Waiting: "Waiting",
    bookingtab_Booked: "Booked",
    bookingtab_Complete: "Completed",
    waitingscreen_Service_Type: "Service Type:",
    waitingscreen_Mobile_Number: "Mobile Number:",
    waitingscreen_Comment: "Comment:",
    waitingscreen_Time: "Time:",
    waitingscreen_Customer_work_request_time: "Customer work request time",
    waitingscreen_Work_offer_time: "Work offer time",
    waitingscreen_Enter_price: "Enter price",
    waitingscreen_Enter_your_comment_Optional: "Enter your comment (Optional)",
    bookingscreen_Charges: "Charges:",
    bookingscreen_Comment: "Comment:",
    settingscreen_Notification: "Notification",
    settingscreen_Contact_us: "Contact Us",
    settingscreen_Logout: "Logout",
    contactusscreen_Subject: "Subject",
    contactusscreen_Details: "Details",
    subscriptionscreen_Cancel_Subscription: "Cancel Subscription",
    subscriptionscreen_Subscription_fee: "Subscription fee:",
    subscriptionscreen_per_Month: "per Month",
    subscriptionscreen_Yearly: "Yearly \n Save upto 15% with an yearly plan",
    subscriptionscreen_Monthly: "Monthly",
    subscriptionscreen_Enter_Year: "Enter Year",
    subscriptionscreen_Enter_Month: "Enter Month",
    subscriptionscreen_Total_fee: "Total fee:",

    //SURE?
    sure_Are_you_sure_to_exit: "Are you sure to exit?",
    sure_Are_you_sure_to_delete: "Are you sure to delete?",
    sure_Are_you_sure_to_reject: "Are you sure to reject?",
    sure_Are_you_sure_to_unsubsribe_services:
      "Are you sure to unsubsribe services?",
    sure_Work_Completed: "Work Completed?",

    // BUTTONS
    button_Click_to_Upload_Image: "Click to Upload Image",
    button_Save: "Save",
    button_Exit: "Exit",
    button_Add: "Add",
    button_Update: "Update",
    button_Send: "Send",
    button_Apply: "Apply",
    button_Reject: "Reject",
    button_Accept: "Accept",
    button_Message: "Message",
    button_Delete: "Delete",
    button_Help: "Help",
    button_OK: "OK",
    button_Cancel: "Cancel",
    button_Yes: "Yes",
    button_No: "No",
    button_Submit: "Submit",
    button_Done: "Done",
    button_Close: "Close",
    button_Finish: "Finish",
    button_Continue_with_facebook: "Continue with facebook",
    button_Cancel_All: "Cancel All",
    button_Paypal_Check_Out: "Paypal Check Out",

    //others
    No_Booked_Request_Yet: "No Booked Request Yet!",
    No_order_is_completed_yet: "No order is completed yet!",
    Fees: "Fees:",
    No_Refund: "No Refund",
    Your_Expertise: "Your Expertise?",
    Select_Image: "Select Image",
    No_image_uploaded_yet: "No image uploaded yet!",
    Tone: "Tone",
    Silent: "Silent",
    No_Internet_Connection_Available: "No Internet Connection Available!",
    No_Review_is_placed_yet: "No Review is placed yet!"
  },
  iw: {
    Login: "התחברות",
    Get_Lucky: "קבל מזל CSP",
    mainProfile: "פרופיל",
    mainBooking: "הזמנה",
    mainInbox: "תיבת הדואר הנכנס",
    mainGallery: "גלריה",
    mainSetting: "הגדרות",
    mainSubscription: "מנוי",
    profiletab_Profile: "פרופיל",
    profiletab_Reviews: "ביקורות",
    profiletab_Services: "שירותים",
    profileupdate_Name: "שם",
    profileupdate_Mobile_Number: "מספר טלפון נייד",
    profileupdate_Bussiness: "עסקיות",
    profileupdate_Address: "כתובת",
    profileupdate_Description: "תיאור",
    serchplacescreen_Search_a_places: "הזן את הכתובת שלך:",
    servicescreen_No_Services_are_available_for_you:
      "אין שירותים זמינים עבורך!",
    bookingtab_Waiting: "מחכה",
    bookingtab_Booked: "הוזמן",
    bookingtab_Complete: "הושלם",
    waitingscreen_Service_Type: "סוג שירות:",
    waitingscreen_Mobile_Number: "מספר טלפון נייד:",
    waitingscreen_Comment: "תגובה:",
    waitingscreen_Time: "זמן:",
    waitingscreen_Customer_work_request_time: "זמן בקשת עבודה של הלקוח",
    waitingscreen_Work_offer_time: "זמן הצעת עבודה",
    waitingscreen_Enter_price: "הזן מחיר",
    waitingscreen_Enter_your_comment_Optional: "הזן את התגובה שלך (אופציונלי)",
    bookingscreen_Charges: "חיובים:",
    bookingscreen_Comment: "תגובה:",
    settingscreen_Notification: "הודעה",
    settingscreen_Contact_us: "תיצור איתנו קשר",
    settingscreen_Logout: "להתנתק",
    contactusscreen_Subject: "נושא",
    contactusscreen_Details: "פרטים",
    subscriptionscreen_Cancel_Subscription: "בטל רישום",
    subscriptionscreen_Subscription_fee: "דמי מנוי:",
    subscriptionscreen_per_Month: "לחודש",
    subscriptionscreen_Yearly: "שנתי \n חסוך עד 15% באמצעות תוכנית שנתית",
    subscriptionscreen_Monthly: "חודשי",
    subscriptionscreen_Enter_Year: "הזן שנה",
    subscriptionscreen_Enter_Month: "הכנס חודש",
    subscriptionscreen_Total_fee: "סכום כולל:",

    //SURE?
    sure_Are_you_sure_to_exit: "האם אתה בטוח שברצונך לצאת?",
    sure_Are_you_sure_to_delete: "האם אתה בטוח למחוק אותו?",
    sure_Are_you_sure_to_reject: "האם אתה בטוח לדחות?",
    sure_Are_you_sure_to_unsubsribe_services:
      "האם אתה בטוח לבטל את הרישום לשירותים?",
    sure_Work_Completed: "העבודה הושלמה?",

    // BUTTONS
    button_Click_to_Upload_Image: "לחץ כדי להעלות תמונה",
    button_Save: "לשמור",
    button_Exit: "יציאה",
    button_Add: "הוסף",
    button_Update: "עדכון",
    button_Send: "שלח",
    button_Apply: "להגיש מועמדות",
    button_Reject: "דחה",
    button_Accept: "קבל",
    button_Message: "הודעה",
    button_Delete: "מחק",
    button_Help: "עזרה",
    button_OK: "בסדר",
    button_Cancel: "בטל",
    button_Yes: "כן",
    button_No: "לא",
    button_Submit: "שלח",
    button_Done: "בוצע",
    button_Close: "קרוב",
    button_Finish: "סיום",
    button_Continue_with_facebook: "המשך עם פייסבוק",
    button_Cancel_All: "בטל הכל",
    button_Paypal_Check_Out: "Paypal צ'ק אאוט",

    //others
    No_Booked_Request_Yet: "אין עדיין בקשה שהוזמנה!",
    No_order_is_completed_yet: "ההזמנה לא הושלמה עדיין!",
    Fees: "אגרות:",
    No_Refund: "ללא החזר",
    Your_Expertise: "המומחיות שלך?",
    Select_Image: "בחר תמונה",
    No_image_uploaded_yet: "טרם הועלתה תמונה!",
    Tone: "טון",
    Silent: "שקט",
    No_Internet_Connection_Available: "אין חיבור לאינטרנט זמין!",
    No_Review_is_placed_yet: "טרם הועלה ביקורת!"
  },
  ur: {
    mainProfile: "پروفائل"
  }
});

export default strings;
